# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'image-viewer' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for image-viewer
#pod 'YYWebImage', '~> 1.0.5'
end
